#! /bin/bash
# ----------------------------------------
# Constants
# ----------------------------------------
readonly verStr="3.0"
readonly uninitialized="UNINITIALIZED"

# ----------------------------------------
# Globals
# ----------------------------------------
debug="TRUE"
debug="FALSE"

# ----------------------------------------------------------------------
# MAIN Main main
# ----------------------------------------------------------------------

descStr="$*"
if [[ -z $1 ]]; then
        descStr=DESC
else
        descStr=$*   #! Remainder of the command line
        if [ "$debug" == "TRUE" ]; then
            echo "0 ........................ $0"
            echo "1 ........................ $1"
            echo "verStr ................... $verStr"
            echo "descStr .................. $descStr"
            echo "<remainder> .............. $*"
        fi
fi

actionDesc="$*"
if [[ -z $actionDesc ]]; then
	actionDesc="desc"
fi

dateStr=$(date "+%m-%d")

printf "A::${verStr}::I::${dateStr}::${descStr}::\n"

# ----------------------------------------------------------------------
# END End end
# ----------------------------------------------------------------------
  exit  #! So the rest of the file is not executed
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------
# Description
# ----------------------------------------
Create a record for an action item


A::${verStr}::I::${dateStr}::${descStr}::

Format Description

A::<ver>::<state>::<date>::<desc>::<remainder>

    "A"          Indicates that this is a "action" record
    <ver>        Script version
    <state>      Record state. "I" = "Initial", "C" = "Complete"
    <date>       Creation date. MM-DD format.
    <desc>       Action item description
    <remainder>  Fre-form text

# ----------------------------------------

# ----------------------------------------
# History
# ----------------------------------------


# ----------------------------------------------------------------------
v3.0 
- Rewrite the majority
- Shorten the format

- Shorten the record to make more room 
- Can now supply an argument. It becomes the DESC value in the record.
- Major restructure to be consistent with more current scripts, timerec

# ----------------------------------------------------------------------
v2.0 - I don't recall

dateStr=$(date "+%Y-%m-xx")

printf "A::${ver}::${name}::${actionDesc}::I::${dateStr}::desc::\n"

# ----------------------------------------------------------------------
v1.3 - Add double quotes around the $*
     - Add braces around vars in the printf string
v1.2 - $* was the owner name. Is now the "actionDesc" string.
v1.1 - Initial version


