#! /bin/bash

nameStr="$*"
if [[ -z $nameStr ]]; then
	descStr="DESCRIPTION"
fi

verStr="1.0"

dayStr=$(date "+%a")
dateStr=$(date "+%Y-%m-%d")
timeStr=$(date "+%H:%M:%S")

printf "CHAL::$verStr::$dayStr::$dateStr::$descStr::\n"

# v1.0 - Initial version
#CHAL::1.0::Mon::2017-03-20::UNITIALIZED::
