#! /bin/bash

# ----------------------------------------
# Constants
# ----------------------------------------

readonly verStr="4.0"
readonly uninitialized="UNINITIALIZED"

# ----------------------------------------
# ----------------------------------------
# main Main MAIN
# ----------------------------------------
# ----------------------------------------

nameStr="$*"
if [[ -z $nameStr ]]; then
	firstStr="FIRST"
fi

lastStr="LAST"
emailStr="EMAIL"
phoneStr="PHONE"
coStr="COMPANY"
roleStr="ROLE"

dayStr=$(date "+%a")
dateStr=$(date "+%Y-%m-%d")
timeStr=$(date "+%H:%M:%S")

#Ver 2.0: printf "CONREC::$dateStr::$verStr::$nameStr::$emailStr::$phoneStr::$coStr::\n"
#ver 3.0: printf "CONREC::$dateStr::$verStr::$firstStr::$lastStr::$emailStr::$phoneStr::$coStr::\n"

# Version 4.0
printf "CONREC::$verStr::$dateStr::$firstStr::$lastStr::$emailStr::$phoneStr::$coStr::$roleStr::"
printf "\n"

# ----------------------------------------
# ----------------------------------------
  exit  # Without this, the comment section will execute and error out.
# ----------------------------------------
# ----------------------------------------

#
# Create a record for contact information
#

# ----------------------------------------------------------------------
# 2018-04-20
# Version 4.0
# Compatible with CONREC version 3.0
# ----------------------------------------------------------------------
LOTS of changes in structure. Mature, refactor, cleanup
Move the record version number from token 


# v3.0 - Break "name" into "first" and "last"
CONREC::2018-04-20::3.0::record ver::FIRST::LAST::EMAIL::PHONE::COMPANY::

# v2.0 - Add company name
CONREC::2014-08-27::2.0::NAME::EMAIL::PHONE::COMPANY::

# v1.0 - Initial version
# Record format:
# <preamble fields>::<name>::<email>::<phone>::
# CONREC::2014-08-27::1.0::NAME::EMAIL::PHONE::
# 
# 
