#! /bin/bash
datestr="+%Y-%m-%d %H:%M:%S %Z %a"
timestamp=$(/bin/date "$datestr")
echo ""
echo "# ======================================================================"
echo "# ======================================================================"
echo "EntryVersion::3.0"
echo "Timestamp::$timestamp"
echo ""
