#! /bin/zsh

meetCount=40
staffCount=10
journalFile="${HOME}/sync_synology/doc/journal/work/journal_work.txt"

echo ""
echo "------------------------------------------------------------"
echo ""

#grep  -n '- MEET:\|Client Staff::' "${journalFile}" | grep -v TIME:: | head -${meetCount}
grep  -n -m $meetCount -e'- MEET:' -e'Client Staff::' "${journalFile}" | grep -v TIME:: 

echo ""
echo "------------------------------------------------------------"
echo ""

#grep -n 'Client Staff:: ' ${journalFile} | head -$staffCount
