#! /bin/bash

# ----------------------------------------
# Constants
# ----------------------------------------
readonly verStr="4.1"
readonly uninitialized="UNINITIALIZED"

# ----------------------------------------------------------------------
# MAIN Main main
# ----------------------------------------------------------------------

#echo "0 ........................ $0"	#debug
#echo "1 ........................ $1"	#debug
#echo "clientStr ................ $clientStr"	#debug

clientStr="$*"
if [[ -z $1 ]]; then
	clientStr=CLIENT
else
	clientStr=$*   #! Remainder of the command line
	#echo "0 ........................ $0"	#debug
	#echo "1 ........................ $1"	#debug
	#echo "verStr ................... $verStr"	#debug
	#echo "clientStr ................ $clientStr"	#debug
	#echo "<remainder> .............. $*"	#debug

fi

startStr=START
endStr=END
elapsedStr=ELAPSED
commentStr=COMMENT

# This indicates the record is in a "new" state.
stateStr=new

dayStr=$(date "+%a")
dateStr=$(date "+%Y-%m-%d")
timeStr=$(date "+%H.%M.%S")

	#echo "<remainder> .............. $*"	#debug
	#echo "<remainder> .............. $*"	#debug
	#echo "<remainder> .............. $*"	#debug

printf "TIME::$verStr::$dayStr::$dateStr::$startStr::$endStr::$elapsedStr::$clientStr::$stateStr::$commentStr::\n"

# ----------------------------------------------------------------------
# END End end
# ----------------------------------------------------------------------
  exit  #! So the rest of the file is not executed
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------


# ----------------------------------------
# Description
# ----------------------------------------
Create a record for contact information

TIME::$verStr::$dateStr::$startStr::$endStr::$elapsedStr::$clientStr::$commentStr::

# ----------------------------------------

# ----------------------------------------
# History
# ----------------------------------------

# ----------------------------------------
v4.1 - No code change!
       User input changing. This is a change in data entry only.
       Changed from: hrs.min
       Changed to:   hrs.fraction of an hour

       As an example
       Changed from: 01.15
       Changed to:   01.25

v4.0 - Change time field seperator from ":" to ".".
       Makes parsing much easier in other scripts.
       No changes required to this script for the sepearator change. This
       comment is to ensure the intent is understood for any future changes.

       Added a <state> field. This field is set to "n" for "new". It can be
       changed to other values and used by other scripts.
TIME::4.0::Fri::2018-05-11::START::END::ELAPSED::Client name::new::COMMENT::

# ----------------------------------------
v3.3 - Reverse the order of $dateStr and $dayStr
v3.4 - Many small changes
  - 2018.05.05
  - Add "readonly" for constants
  - Add script section dividers
  - Add the "exit"
  - Better structured the "History" section
  - Fix <where> to be $* to get the remainder of the command line
  - Changed WHERE clause to CLIENT
Initialization was all messed up. Fix.
Command line param is CLIENT>. $clientStr set to $1

TIME::3.3::Tue::2018-04-10::START::END::ELAPSED::WHERE::COMMENT::
TIME::3.4::Sat::2018-05-05::START::END::ELAPSED::Sample client WHERE clause::COMMENT::

# ----------------------------------------
v3.2 - Reverse the order of $dateStr and $dayStr
Makes this and the "daily" script consistent
TIME::3.2::Mon::2017-03-27::START::END::ELAPSED::WHERE::COMMENT::

# ----------------------------------------
v3.1 - Add a "where" string
Bug fix. Dropped the dayStr from the record. Add back.
TIME::3.1::2017-03-04::Sat::START::END::ELAPSED::WHERE::COMMENT::

# ----------------------------------------
v3.0 - Add a "where" string
Location is now separate from the comment
TIME::3.0::2017-02-25::START::END::ELAPSED::WHERE::COMMENT::

# ----------------------------------------
v2.0 - Add a date string
Makes grep'ing the log file easier.
TIME::$verStr::$dateStr::$startStr::$endStr::$elapsedStr::$commentStr::

# ----------------------------------------
v1.0 - Initial version
Record format:
TIME::$verStr::$startStr::$endStr::$elapsedStr::$commentStr::


